version: '3.8'

services:
  database:
    build:
      context: ./sql
      dockerfile: Dockerfile
    ports:
      - "3456:3456"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend