version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database
 
 
  database:
       build:
         context: ./sql
       ports:
         - "3306:3306" 
      # command: ["mysqld", "--plugin-load=itay"]     