version: '3.8'

services:
  backend: 
    image: backend-fin
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@database:3306/USERS
    networks:
      - app-network


  database:
    image: blog
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: USERS
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge

volumes:
  mysqldata: