## fixiing!!!!!!!!!!!!1

version: '3.8'

services:
  backend:
    build: 
         context: ./backend
         dockerfile: Dockerfile
        
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql+pymysql://root:my-secret-pw@database:3456/USERS
    networks:
      - app-network


  database:
  
    image: csdb:Dockerfile1.0
    restart: always
    ports:
      - 3456:80
    networks:
      - app-network
      
networks:
  app-network:
    #driver: bridge

volumes:
  mysqldata:

  #frontend:
    # Define your frontend service here
    # Replace this section with your actual frontend service configuration
    # Example:
    # build: ./frontend
    # ports:
    #   - "3000:3000"
    # Depends_on:
    #   - backend
    # networks:
    #   - app-network

